proof-of-concept for CocoaPodsIntegration

diff --git a/objc-run b/objc-run
--- a/objc-run
+++ b/objc-run
@@ -1,35 +1,378 @@
 #!/bin/bash
 
-if [[ $# -lt 1 ]]; then 
-	echo "objc-run usage: objc-run file.m [params]" 1>&2
-	exit 1
-fi
+function main
+{
+	if [[ $# -lt 1 ]]; then 
+		echo "objc-run usage: objc-run file.m [params]" 1>&2
+		exit 1
+	fi
 
-filepath="$1"
-filename="$(basename "$filepath")"
-appname="${filename%.*}"
-target="$(dirname "$filepath")/$appname"
-shift
+	#check if the source file contains an embedded podfile for CocoaPods
 
-# check if there's already a file with the same name as our compiled app, if so exit
-if [[ -f "$target" ]]; then
-	echo "objc-run: file already exists at $dirname/$appname ... exiting" 1>&2
-	exit 1
-fi
+	podstart=`awk '/podfile-start/{print NR+1}' $1`
+	podend=`awk '/podfile-end/{print NR-1}' $1`
 
-# compile the file
-# remove shebangs on first line, first chars only
-clang -o "$target" -Wall -std=c99 -framework Foundation -lobjc -fobjc-arc -fmodules -x objective-c <(awk 'NR>1 || !/^#!/' "$filepath")
-clangExitCode=$?
+	if [ ${#podstart} -gt 0 ]
+	then
+		handleSourceFileWithCocoaPods "$@"
+	else
+		handleSourceFileWithoutCocoaPods "$@"
+	fi
+}
 
-# on clang success, run compiled application and remove it
-if [[ $clangExitCode -eq 0 ]]; then 
-	"$target" "$@"
-	rm -f "$target"
-else
-	echo "objc-run usage: clang returned with error" 1>&2
-	exit 1
-fi
+function handleSourceFileWithoutCocoaPods
+{
+	filepath="$1"
+	filename="$(basename "$filepath")"
+	appname="${filename%.*}"
+	target="$(dirname "$filepath")/$appname"
+	shift
 
-# exit explicitly with no error
-exit 0
+	# check if there's already a file with the same name as our compiled app, if so exit
+	if [[ -f "$target" ]]; then
+		echo "objc-run: file already exists at $dirname/$appname ... exiting" 1>&2
+		exit 1
+	fi
+
+	# compile the file
+	# remove shebangs on first line, first chars only
+	clang -o "$target" -Wall -std=c99 -framework Foundation -lobjc -fobjc-arc -fmodules -x objective-c <(awk 'NR>1 || !/^#!/' "$filepath")
+	clangExitCode=$?
+
+	# on clang success, run compiled application and remove it
+	if [[ $clangExitCode -eq 0 ]]; then 
+		"$target" "$@"
+		rm -f "$target"
+	else
+		echo "objc-run: clang returned with error" 1>&2
+		exit 1
+	fi
+
+	# exit explicitly with no error
+	exit 0
+}
+
+function handleSourceFileWithCocoaPods
+{
+	filepath="$1"
+	filename="$(basename "$filepath")"
+	appname="${filename%.*}"
+	target="$(dirname "$filepath")/$appname"
+	shift
+	
+	# check if there's already a file with the same name as our compiled app, if so exit
+	if [[ -f "$target" ]]; then
+		echo "objc-run: file already exists at $dirname/$appname ... exiting" 1>&2
+		exit 1
+	fi
+	
+	# check if a  temporary project directory already exists, if not create it
+	sourePathHash=`md5 -qs "$filepath"`
+	projectDirPath="${TMPDIR}objc-run/$sourePathHash"
+	if [ ! -d $projectDirPath ]
+	then
+		createProjectDirectory "$projectDirPath"
+	fi
+
+	#copy source file into temp dir, removing shebang
+	awk 'NR>1 || !/^#!/' "$filepath" > "$projectDirPath/main.m"
+	
+	#extract embedded podfile and save it into projectdir
+	podstart=`awk '/podfile-start/{print NR+1}' $filepath`
+	podend=`awk '/podfile-end/{print NR-1}' $filepath`
+	sed -n ${podstart},${podend}p $filepath > "$projectDirPath/podfile.new"
+	
+	(
+		cd "$projectDirPath"
+
+		if [ ! -f podfile ]
+		then
+			mv podfile.new podfile
+			echo "Installing pod"
+			pod install
+		else
+			if ! diff podfile.new podfile >/dev/null 2>&1
+			then
+				echo "Updating pod"
+				mv -f podfile.new podfile
+				pod update
+			else
+				rm podfile.new
+			fi
+		fi
+		
+	)
+	xcodebuild -workspace "$projectDirPath/clitest.xcworkspace/" -scheme clitest -configuration Release DEPLOYMENT_LOCATION=YES DSTROOT=build DWARF_DSYM_FOLDER_PATH=build 
+	xcodebuildExitCode=$?
+
+	# on clang success, run compiled application and remove it
+	if [[ $xcodebuildExitCode -eq 0 ]]; then 
+		cp "$projectDirPath/build/usr/local/bin/clitest" $target
+		trap '{ rm -f "$target" ; exit 1; }' INT
+		"$target" "$@"
+		trap '' INT
+		rm -f "$target"
+	else
+		echo "objc-run: xcodebuild returned with error" 1>&2
+		exit 1
+	fi
+	
+	open "$projectDirPath"
+
+	exit 0
+}
+
+function writePCHfile
+{
+read -d '' String <<"EOF"
+#ifdef __OBJC__
+	#import <Foundation/Foundation.h>
+#endif
+
+EOF
+echo "${String}" > $1
+}
+
+function writePBXFile
+{
+read -d '' String <<"EOF"
+// !$*UTF8*$!
+{
+	archiveVersion = 1;
+	classes = {
+	};
+	objectVersion = 46;
+	objects = {
+
+/* Begin PBXBuildFile section */
+		4D208C1F1882E49700450167 /* main.m in Sources */ = {isa = PBXBuildFile; fileRef = 4D208C1E1882E49700450167 /* main.m */; };
+		4DD0EFF01872D51F00DC2102 /* Foundation.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = 4DD0EFEF1872D51F00DC2102 /* Foundation.framework */; };
+/* End PBXBuildFile section */
+
+/* Begin PBXFileReference section */
+		4D208C1E1882E49700450167 /* main.m */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.objc; path = main.m; sourceTree = SOURCE_ROOT; };
+		4D208C201882E49F00450167 /* clitest-Prefix.pch */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.h; path = "clitest-Prefix.pch"; sourceTree = SOURCE_ROOT; };
+		4DD0EFEC1872D51F00DC2102 /* clitest */ = {isa = PBXFileReference; explicitFileType = "compiled.mach-o.executable"; includeInIndex = 0; path = clitest; sourceTree = BUILT_PRODUCTS_DIR; };
+		4DD0EFEF1872D51F00DC2102 /* Foundation.framework */ = {isa = PBXFileReference; lastKnownFileType = wrapper.framework; name = Foundation.framework; path = System/Library/Frameworks/Foundation.framework; sourceTree = SDKROOT; };
+/* End PBXFileReference section */
+
+/* Begin PBXFrameworksBuildPhase section */
+		4DD0EFE91872D51F00DC2102 /* Frameworks */ = {
+			isa = PBXFrameworksBuildPhase;
+			buildActionMask = 2147483647;
+			files = (
+				4DD0EFF01872D51F00DC2102 /* Foundation.framework in Frameworks */,
+			);
+			runOnlyForDeploymentPostprocessing = 0;
+		};
+/* End PBXFrameworksBuildPhase section */
+
+/* Begin PBXGroup section */
+		4DD0EFE31872D51F00DC2102 = {
+			isa = PBXGroup;
+			children = (
+				4D208C1E1882E49700450167 /* main.m */,
+				4D208C201882E49F00450167 /* clitest-Prefix.pch */,
+				4DD0EFEF1872D51F00DC2102 /* Foundation.framework */,
+				4DD0EFED1872D51F00DC2102 /* Products */,
+			);
+			sourceTree = "<group>";
+		};
+		4DD0EFED1872D51F00DC2102 /* Products */ = {
+			isa = PBXGroup;
+			children = (
+				4DD0EFEC1872D51F00DC2102 /* clitest */,
+			);
+			name = Products;
+			sourceTree = "<group>";
+		};
+/* End PBXGroup section */
+
+/* Begin PBXNativeTarget section */
+		4DD0EFEB1872D51F00DC2102 /* clitest */ = {
+			isa = PBXNativeTarget;
+			buildConfigurationList = 4DD0EFFA1872D51F00DC2102 /* Build configuration list for PBXNativeTarget "clitest" */;
+			buildPhases = (
+				4DD0EFE81872D51F00DC2102 /* Sources */,
+				4DD0EFE91872D51F00DC2102 /* Frameworks */,
+			);
+			buildRules = (
+			);
+			dependencies = (
+			);
+			name = clitest;
+			productName = clitest;
+			productReference = 4DD0EFEC1872D51F00DC2102 /* clitest */;
+			productType = "com.apple.product-type.tool";
+		};
+/* End PBXNativeTarget section */
+
+/* Begin PBXProject section */
+		4DD0EFE41872D51F00DC2102 /* Project object */ = {
+			isa = PBXProject;
+			attributes = {
+				LastUpgradeCheck = 0500;
+				ORGANIZATIONNAME = "iwascoding GmbH";
+			};
+			buildConfigurationList = 4DD0EFE71872D51F00DC2102 /* Build configuration list for PBXProject "clitest" */;
+			compatibilityVersion = "Xcode 3.2";
+			developmentRegion = English;
+			hasScannedForEncodings = 0;
+			knownRegions = (
+				en,
+			);
+			mainGroup = 4DD0EFE31872D51F00DC2102;
+			productRefGroup = 4DD0EFED1872D51F00DC2102 /* Products */;
+			projectDirPath = "";
+			projectRoot = "";
+			targets = (
+				4DD0EFEB1872D51F00DC2102 /* clitest */,
+			);
+		};
+/* End PBXProject section */
+
+/* Begin PBXSourcesBuildPhase section */
+		4DD0EFE81872D51F00DC2102 /* Sources */ = {
+			isa = PBXSourcesBuildPhase;
+			buildActionMask = 2147483647;
+			files = (
+				4D208C1F1882E49700450167 /* main.m in Sources */,
+			);
+			runOnlyForDeploymentPostprocessing = 0;
+		};
+/* End PBXSourcesBuildPhase section */
+
+/* Begin XCBuildConfiguration section */
+		4DD0EFF81872D51F00DC2102 /* Debug */ = {
+			isa = XCBuildConfiguration;
+			buildSettings = {
+				ALWAYS_SEARCH_USER_PATHS = NO;
+				CLANG_CXX_LANGUAGE_STANDARD = "gnu++0x";
+				CLANG_CXX_LIBRARY = "libc++";
+				CLANG_ENABLE_OBJC_ARC = YES;
+				CLANG_WARN_BOOL_CONVERSION = YES;
+				CLANG_WARN_CONSTANT_CONVERSION = YES;
+				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
+				CLANG_WARN_EMPTY_BODY = YES;
+				CLANG_WARN_ENUM_CONVERSION = YES;
+				CLANG_WARN_INT_CONVERSION = YES;
+				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
+				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
+				COPY_PHASE_STRIP = NO;
+				GCC_C_LANGUAGE_STANDARD = gnu99;
+				GCC_DYNAMIC_NO_PIC = NO;
+				GCC_ENABLE_OBJC_EXCEPTIONS = YES;
+				GCC_OPTIMIZATION_LEVEL = 0;
+				GCC_PREPROCESSOR_DEFINITIONS = (
+					"DEBUG=1",
+					"$(inherited)",
+				);
+				GCC_SYMBOLS_PRIVATE_EXTERN = NO;
+				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
+				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
+				GCC_WARN_UNDECLARED_SELECTOR = YES;
+				GCC_WARN_UNINITIALIZED_AUTOS = YES;
+				GCC_WARN_UNUSED_FUNCTION = YES;
+				GCC_WARN_UNUSED_VARIABLE = YES;
+				MACOSX_DEPLOYMENT_TARGET = 10.9;
+				ONLY_ACTIVE_ARCH = YES;
+				SDKROOT = macosx;
+			};
+			name = Debug;
+		};
+		4DD0EFF91872D51F00DC2102 /* Release */ = {
+			isa = XCBuildConfiguration;
+			buildSettings = {
+				ALWAYS_SEARCH_USER_PATHS = NO;
+				CLANG_CXX_LANGUAGE_STANDARD = "gnu++0x";
+				CLANG_CXX_LIBRARY = "libc++";
+				CLANG_ENABLE_OBJC_ARC = YES;
+				CLANG_WARN_BOOL_CONVERSION = YES;
+				CLANG_WARN_CONSTANT_CONVERSION = YES;
+				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
+				CLANG_WARN_EMPTY_BODY = YES;
+				CLANG_WARN_ENUM_CONVERSION = YES;
+				CLANG_WARN_INT_CONVERSION = YES;
+				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
+				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
+				COPY_PHASE_STRIP = YES;
+				DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
+				ENABLE_NS_ASSERTIONS = NO;
+				GCC_C_LANGUAGE_STANDARD = gnu99;
+				GCC_ENABLE_OBJC_EXCEPTIONS = YES;
+				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
+				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
+				GCC_WARN_UNDECLARED_SELECTOR = YES;
+				GCC_WARN_UNINITIALIZED_AUTOS = YES;
+				GCC_WARN_UNUSED_FUNCTION = YES;
+				GCC_WARN_UNUSED_VARIABLE = YES;
+				MACOSX_DEPLOYMENT_TARGET = 10.9;
+				SDKROOT = macosx;
+			};
+			name = Release;
+		};
+		4DD0EFFB1872D51F00DC2102 /* Debug */ = {
+			isa = XCBuildConfiguration;
+			buildSettings = {
+				CLANG_ENABLE_MODULES = YES;
+				GCC_PRECOMPILE_PREFIX_HEADER = YES;
+				GCC_PREFIX_HEADER = "clitest-Prefix.pch";
+				PRODUCT_NAME = "$(TARGET_NAME)";
+			};
+			name = Debug;
+		};
+		4DD0EFFC1872D51F00DC2102 /* Release */ = {
+			isa = XCBuildConfiguration;
+			buildSettings = {
+				CLANG_ENABLE_MODULES = YES;
+				GCC_PRECOMPILE_PREFIX_HEADER = YES;
+				GCC_PREFIX_HEADER = "clitest-Prefix.pch";
+				PRODUCT_NAME = "$(TARGET_NAME)";
+			};
+			name = Release;
+		};
+/* End XCBuildConfiguration section */
+
+/* Begin XCConfigurationList section */
+		4DD0EFE71872D51F00DC2102 /* Build configuration list for PBXProject "clitest" */ = {
+			isa = XCConfigurationList;
+			buildConfigurations = (
+				4DD0EFF81872D51F00DC2102 /* Debug */,
+				4DD0EFF91872D51F00DC2102 /* Release */,
+			);
+			defaultConfigurationIsVisible = 0;
+			defaultConfigurationName = Release;
+		};
+		4DD0EFFA1872D51F00DC2102 /* Build configuration list for PBXNativeTarget "clitest" */ = {
+			isa = XCConfigurationList;
+			buildConfigurations = (
+				4DD0EFFB1872D51F00DC2102 /* Debug */,
+				4DD0EFFC1872D51F00DC2102 /* Release */,
+			);
+			defaultConfigurationIsVisible = 0;
+			defaultConfigurationName = Release;
+		};
+/* End XCConfigurationList section */
+	};
+	rootObject = 4DD0EFE41872D51F00DC2102 /* Project object */;
+}
+
+EOF
+
+echo "${String}" > $1
+}
+
+function createXcodeProjectPackage
+{
+	mkdir "$1"
+	writePBXFile "$1/project.pbxproj"
+}
+
+function createProjectDirectory
+{
+	mkdir -p "$1"
+	createXcodeProjectPackage "$1/clitest.xcodeproj"
+	writePCHfile "$1/clitest-Prefix.pch"
+}
+
+main "$@"
